from app.tasks import niche_tasks  # noqa: F401
from app.tasks import learning_tasks  # noqa: F401
from app.tasks import gamification_tasks  # noqa: F401
from app.tasks import store_tasks  # noqa: F401
from app.tasks import repair_tasks  # noqa: F401
from app.tasks import outbox_tasks  # noqa: F401
from app.tasks import dispute_tasks  # noqa: F401
from app.tasks import launch_ops_tasks  # noqa: F401
from app.tasks import proof_of_gigs_tasks  # noqa: F401
from app.tasks import payouts_tasks  # noqa: F401
