export const queryKeys = {
  me: ["me"] as const,
  analytics: ["analytics"] as const,
  admin: {
    users: (params?: unknown) => ["admin", "users", params] as const,
    userDetail: (userId: string) => ["admin", "users", userId] as const,
    payouts: (params?: unknown) => ["admin", "payouts", params] as const,
    disputes: (params?: unknown) => ["admin", "disputes", params] as const,
    refunds: (params?: unknown) => ["admin", "refunds", params] as const,
    flags: ["admin", "feature-flags"] as const,
    aiFlags: ["admin", "ai-feature-flags"] as const,
    rolloutCities: ["admin", "rollout-cities"] as const,
    rolloutOverride: (userId: string) => ["admin", "rollout-override", userId] as const,
    riskUsers: (params?: unknown) => ["admin", "risk-users", params] as const,
    riskUser: (userId: string) => ["admin", "risk-user", userId] as const,
    riskRules: ["admin", "risk-rules"] as const,
    abuseSignals: (params?: unknown) => ["admin", "abuse-signals", params] as const,
    onboardingPros: (params?: unknown) => ["admin", "onboarding-pros", params] as const,
    searchStatus: ["admin", "search-status"] as const,
    notificationsLogs: (params?: unknown) => ["admin", "notification-logs", params] as const,
    metricsSummary: ["admin", "metrics-summary"] as const,
    consentEvents: (params?: unknown) => ["admin", "consent-events", params] as const,
    rewards: ["admin", "rewards"] as const,
    invitesWaves: ["admin", "invite-waves"] as const,
    invitesCodes: (params?: unknown) => ["admin", "invite-codes", params] as const,
    i18nLocales: ["admin", "i18n-locales"] as const,
    i18nBundles: ["admin", "i18n-bundles"] as const,
    i18nMissingKeys: ["admin", "i18n-missing-keys"] as const,
    printsOrders: (params?: unknown) => ["admin", "prints-orders", params] as const,
    printsProducts: ["admin", "prints-products"] as const,
    printsPartners: ["admin", "prints-partners"] as const,
    storePolicy: ["admin", "store-policy"] as const,
    storePartners: ["admin", "store-partners"] as const,
    storeProducts: (params?: unknown) => ["admin", "store-products", params] as const,
    storePriceRules: ["admin", "store-price-rules"] as const,
    studioversePacks: (params?: unknown) => ["admin", "studioverse-packs", params] as const,
    repairsPartners: ["admin", "repairs-partners"] as const,
    repairsPolicy: ["admin", "repairs-policy"] as const,
    repairsTickets: (params?: unknown) => ["admin", "repairs-tickets", params] as const,
    repairsLoaners: (params?: unknown) => ["admin", "repairs-loaners", params] as const,
    rawwCaps: ["admin", "raww-caps"] as const,
    rawwIssuanceRules: ["admin", "raww-issuance-rules"] as const,
    rawwMultiplierPolicy: ["admin", "raww-multiplier-policy"] as const,
    rawwMints: (params?: unknown) => ["admin", "raww-mints", params] as const,
    financeFeePolicy: ["admin", "finance-fee-policy"] as const,
    financePros: (params?: unknown) => ["admin", "finance-pros", params] as const,
    financeProDetail: (id: string) => ["admin", "finance-pro-detail", id] as const
  }
};
